### ISSUE TITLE
학습진행이 안되는거 같아요.

### ISSUE THREAD

**Issue by sechan-hwang** [sh951011/Korean-Speech-Recognition#1]
[2020-03-05 14:23:06,776 main.py:122 - <module>()] start
여기까진 진행이 되었는데 그 이후 아무반응이 없습니다. 혹시 짐작가시는게 있으시면 도움을 주세요. 
혹시 멀티 GPU가 원인일수도 있나요? 
2080 Ti 두개가 연결된 우분투환경에서 진행중입니다.

**Comment by sh951011** [comment]
안녕하세요 !

학습 진행중에 멈추셨다고 하셨는데 혹시

어떤 데이터셋으로 어떻게 학습진행하셨는지

여쭤봐도 될까요?

데이터쪽에서 전처리가 필요한 작업이라 그럴수도 있을 것 같습니다!

2020년 3월 5일 (목) 오후 2:29, sechan-hwang <notifications@github.com>님이 작성:

**Comment by sechan-hwang** [comment]
AI Hub 데이터 사용했습니다.(1000시간)
문서 참고해서 _label_파일도 생성했습니다.
데이터를 KaiSpeech 위치에 넣고 
utils/define.py 파일을 수정했습니다.
 > DATASET_PATH = "./KaiSpeech/"
그 이후에 python main.py 실행하였습니다..

아래는 변환한 파일중 하나에요.
$ cat ../KaiSpeech/KaiSpeech_label_552475.txt
2 0 41 6 0 415 39 8 0 14 20 29 0 71 100 325 4 11 0 13 129 17 0 8 305 0 8 208 0 153 3 0 13 27 154 0 379 16 0 495 0 415 39 8 55 0 191 68 32 4 9 25 1 0 141 20 0 279 170 0 2 33 18 0 279 170 0 198 8 0 14 13 431 23 0 191 212 171 24 0 94 56 5 1 0 35 11 0 279 170 8 6 0 507 50 1 0 141 117 24 0 27 170 8 4 0 186 83 17 0 191 68 24 0 507 56 5 1 0 52 19 0 66 123 14 7 0 247 24 0 280 65 477 0 8 600 50 0 157 458 3 32 89 0 52 19 0 68 31 18 0 170 8 0 191 230 0 51 0 970 182 31 56 5 1

**Comment by sh951011** [comment]
혹시 그러면 도커를 사용하시는건 아니시고, 로컬로 돌리시는 건가요?
도커를 사용하신다면, setup.py, requirements.txt 등에서 문제가 발생하여 위와 같은 증상이
일어났던 적이 있습니다.

만약 로컬로 돌리시는데 학습 진행이 안되신다면, 디버깅 하셔서 어느 쪽에서 멈추는지 확인부탁드립니다.

**Comment by sechan-hwang** [comment]
conda 가상환경 사용하고 있습니다.
setup.py, requirements.txt이 안보여서 그러는데 어디서 확인이 되는지 알려주실수 있으신가요?

**Comment by sh951011** [comment]
해당 코드가 로컬에서 돌리기 위해 바꾼 코드라 setup.py, requirements.txt는 없앴습니다.
혹시 docker 사용하신다면 문제가 되실 수 있다는 말이였습니다.

![image](https://user-images.githubusercontent.com/42150335/75954750-c0a20c80-5ef7-11ea-8ed1-fdeb1f49a2f7.png)

메인문에서 위 코드와 같이 진행해보시고 결과를 알 수 있을까요??

만약 특정 부분에서 멈춘다면 queue 쪽에서 문제가 생긴 것 같습니다.

**Comment by sh951011** [comment]
현재 같은 코드로 저희 팀은 학습이 원활하게 진행이 되고 있습니다.
현재 저희는 Multi-GPU 환경은 아니지만, 이전에 학습시에 Multi-GPU 환경에서도 원활하게 돌아갔습니다.  

그리고 Multi-GPU를 사용하시려면, main문 상단의 os.environ["CUDA_LAUNCH_BLOCKING"] = "1" 부분은 없애주셔야 되실 겁니다.

**Comment by sechan-hwang** [comment]
#    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
이부분 주석 처리하니 학습이 진행됩니다. 
친절히 대답해 주셔서 감사합니다. ^^

**Comment by sh951011** [comment]
다른 이슈가 생기신다면 언제든지 환영입니다.
감사합니다.

**Comment by sechan-hwang** [comment]
[2020-03-05 16:44:26,274 trainer.py:84 - train()] timestep:  678/150236, loss: 0.3271, cer: 1.00, elapsed: 1.16s 9.71m 0.16h
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (record at /pytorch/aten/src/ATen/cuda/CUDAEvent.h:116)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f0fa49c3193 in /root/anaconda3/envs/pytorch3.5/lib/python3.5/site-packages/torch/lib/libc10.so)

**Comment by sechan-hwang** [comment]
혹시 위와 같은 에러를 보신적 있으신가요? 
학습도중 에러가 발생하네요. ㅠㅜ

**Comment by sh951011** [comment]
CUDA device assert error네요.
한 번 이런 에러가 발생한 적이 있습니다만, 해당 에러는 다양한 환경에서 발생하는 것으로 알고 있습니다.

혹시 많은 분들이 보실 수 있게 Issue에 등록해주실수 있으실까요?

답변은 그쪽에 달아드리겠습니다.

감사합니다.

2020년 3월 5일 (목) 오후 5:07, sechan-hwang <notifications@github.com>님이 작성:

**Comment by sh951011** [comment]
번거로우시겠지만, 해당 이슈로 애로사항을 겪으시는 분들이 있으실 것 같습니다.

감사합니다.

2020년 3월 5일 (목) 오후 5:14, Soohwan Kim <sh951011@gmail.com>님이 작성:
