### ISSUE TITLE
CUDA device assert error 가 발생했어요.도와주세요.

### ISSUE THREAD

**Issue by sechan-hwang** [sh951011/Korean-Speech-Recognition#2]
[2020-03-05 16:44:26,274 trainer.py:84 - train()] timestep:  678/150236, loss: 0.3271, cer: 1.00, elapsed: 1.16s 9.71m 0.16h
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (record at /pytorch/aten/src/ATen/cuda/CUDAEvent.h:116)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f0fa49c3193 in /root/anaconda3/envs/pytorch3.5/lib/python3.5/site-packages/torch/lib/libc10.so)

**Comment by sh951011** [comment]
네. 이슈로 등록해주셔서 감사합니다.

CUDA error: device-side assert triggered 같은 경우는 다양한 환경에서 에러가 나는 것으로 알고 있습니다.  
  
저희 같은 경우는 해당 에러가 트레이닝 데이터의 레이블 숫자와, train_labels.csv의 레이블 숫자가 서로 다를 때 발생했습니다.  
AI Hub에서 저희가 수행하는 전처리를 수행하고 나면 총 2,337개의 문자가 나오게 됩니다.  
저희는 그 중 1번만 등장한 문자들을 제외하게 되면 약 300개의 문자를 줄인 2,039개의 문자로 분류를 할 수 있었기 때문에, 한 번만 등장한 문자들이 포함된 데이터는 제외하고 트레이닝을 했습니다.  
    
혹시 위 과정을 진행하지 않으셨다면 저희와 같은 이유로 발생하는 에러라고 생각됩니다.  
https://sh951011.github.io/Korean-Speech-Recognition/notes/Preparation.html#create-character-labels 해당 과정 링크입니다.  
    
이미 해당 과정을 진행하셨다고 하셨지만, 혹시 빼먹으신 부분이 있을까봐 링크 올립니다.  
  
Create Character Label 부분 참고해주시기 바랍니다.  
  
해당 문서에는 아직 1번씩 등장한 문자들이 포함된 데이터를 빼주는 방법에 대해서는 작성하지 않았습니다만, 원인 파악에 도움이 되지 않으실까 싶습니다.  

감사합니다.

**Comment by sh951011** [comment]
총 분류 가능한 경우는 0 ~ 2,039인데, 2,040 ~ 2,337까지의 레이블이 등장하게 되면 발생할 수 있는 에러입니다.

**Comment by sh951011** [comment]
아니면 저희와 다른 방법으로, 2,337개의 문자로 분류하시는 방법도 해결이 가능한 방법이라고 생각합니다.

**Comment by sechan-hwang** [comment]
제가 이해한건 2337개로 레이블을 만들고 학습시에는 1번만 등장하는 단어가 포함된 데이터는 학습에서 배제하는것으로 이해를 했는데요.

그게 아니라면 혹시
학습시와 테스트시에 레이블의 번호가 다르다는 말씀이신가요?

**Comment by sh951011** [comment]
저희 팀은 처음에는 1번만 등장하는 단어가 포함된 데이터는 테스트데이터로 뺐었습니다만, 이렇게 되면 말씀하신바와 같이 트레이닝 데이터와 테스트 데이터의 레이블 번호가 서로 다르기 때문에, 추가적인 코딩이 꽤 복잡했었습니다. 이렇게 하는 것보다 그냥 60만개의 파일 중 300개 파일 정도는 뺴도 상관이 없을 것 같다는 판단을 하여, 트레이닝, 테스트 모두에서 빼고 진행했습니다. 
  
그래서 저희는 총 2,040개의 문자 레이블 파일로 학습 및 테스트를 진행했습니다.  
만약 이 외에 문자가 입력으로 들어올 시, 언급하신 에러가 나는 상황을 겪은 적이 있었습니다.  
  
확인을 한 번 해보시는 것이 좋을 것 같습니다 !

**Comment by sechan-hwang** [comment]
그럼 2337개를 다 쓰고 싶으면 어느 부분을 수정해야 할까요?

**Comment by sh951011** [comment]
define.py를 아래와 같이 수정해주시면 될 거에요.

![image](https://user-images.githubusercontent.com/42150335/76068866-4c3d9b00-5fd5-11ea-86c1-f2fe77c41927.png)

**Comment by sh951011** [comment]
주석으로 하신 부분을 사용하시면 되십니다.
헷갈리실수 있을거 같아서 다시 말씀드려요.

**Comment by sh951011** [comment]
해결되셨나요?  해결되셨으면 이슈 닫아주시면 감사하겠습니다.

**Comment by sechan-hwang** [comment]
아 넵 해결되었습니다.
이것 저것 해본다고 답이 늦었습니다. 
감사합니다.^^

**Comment by sh951011** [comment]
네네 해결되었다니 다행이네요 !!
저희 팀이 요즘 코드를 수정하느라,
당시 올린 코드 중 빔서치 부분이나 evalutate 부분에서 몇가지 에러사항이 있었던 것 같습니다 ㅠ.ㅠ

evaluate() 부분은 해결했으며, 빔서치 부분은 해결 중에 있습니다.

참고하셔서 코드 수정하시면 될 것 같습니다 !!

**Comment by sechan-hwang** [comment]
참고하겠습니다. ^^

**Comment by sh951011** [comment]
빔서치 부분 역시 해결했습니다.
감사합니다.
