### ISSUE TITLE
프로젝트 관련해 몇 가지 질문드립니다!

### ISSUE THREAD

**Issue by qute012** [sh951011/Korean-Speech-Recognition#7]
안녕하세요. 저는 음성인식에 대해 공부하고 있는 학생입니다.
프로젝트 관련해 몇 가지 질문 피드백 해주시면 감사하겠습니다!

1. 모델의 구조를 보면 input으로 target이 들어가게 되던데 혹시 labeling 되어있지 않은 데이터의 예측도 가능한가요?

2. 혹시 kaldi의 zeroth data로 돌려보신 경험이 있는지 궁금하며, 있으시다면 성능이 궁금합니다. 데이터를 바꾸어 돌려보려고 하는데, train 중 cer과 loss는 감소되는데 validation에서 loss와 cer은 거의 변하지않고 고정적이네요. 실제로 train set과 test set을 valid set으로 사용하였을 때도 아래와 같이 결과가 거의 동일하며, 사진은 혹시 valid set 자체의 성능이 잘 나오지않는가 싶어 valid set을 train set으로 몇 가지 샘플만 학습과 평가에 사용해보았습니다. 그러나 결과는 동일하였습니다. 라벨링은 본 프로젝트에서 선정한 라벨셋과 kaldi에서 출현하는 캐릭터만 따로 수집하여 사용해보았을 때 동일하였습니다. 혹시 이러한 경험이 있으시다면 어떻게 해결하셨는지도 궁금합니다!
![image](https://user-images.githubusercontent.com/33983084/76742568-9fbd9f00-67b4-11ea-99e8-0ff41ba17fb8.png)

**Comment by qute012** [comment]
추가적으로 제가 시도해본점은 softmax를 사용하지 않고, logit을 바로 사용하여 loss function을 크로스 엔트로피로 사용해보았고, drop out을 사용하지않을 때도 결과는 동일했습니다.

데이터는 kaldi의 음성과 자막을 pickle로 먼저 만들어두어 학습하였는데, 전처리는 본 프로젝트에서 collate fn과 extract feature를 똑같이 사용하였습니다.

**Comment by sh951011** [comment]
1. 학습시에는 Teacher forcing으로 학습을 시켜주기 위해서 넣어준 것입니다. (이는 학습을 빨리하기 위함입니다.)  그래서 학습을 어느 정도 시켜준 이후에는 라벨링 되지 않은 데이터 역시 테스트가 가능합니다.  https://www.youtube.com/watch?v=dHJnCqo2gaU 저희 팀에서 전에 학습 시킨 모델로 팀원의 목소리를 녹음해서 추론 시킨 결과입니다. 영상 참고해보시면 될 것 같습니다.

2. kaldi의 zeroth data로 학습을 시켜본적은 없습니다. 저희는 네이버에서 제공한 100시간의 데이터셋과 AI Hub에서 제공한 데이터만을 사용해보았습니다. 주제가 한국어 음성 인식 프로젝트이다보니, 
한국어 음성 데이터만을 사용해봤습니다.   
    
아래 링크에는 전에 저희가 학습시킨 모델의 train / valid / test 했을 때의 결과가 기록되어 있습니다.  
참고하시면 도움이 되실 것 같습니다.  
  
https://github.com/sh951011/Korean-Speech-Recognition/blob/master/docs/training/AI%20Hub%20Dataset%20%232.md   
  
이 외에는 제가 zeroth data에 대한 정보와 질문하신 분이 어떤 설정으로 어떤 하이퍼파라미터로 진행하셨는지에 대한 구체적인 정보가 없어 명확하게 답변드리기가 어려울 것 같습니다 ㅜ.ㅜ  
   
3.  보여주신 결과는 상당히 CER이 낮은 것으로 확인이 됩니다.  
아마 어떠한 문제점이 있지 않나 싶습니다. dropout은 오버피팅을 방지하기 위함인데, 현재 학습 데이터에 대해서도 잘 못 맞추고 있는 것으로 보이기 때문에, 드랍아웃이 존재 유무와 상관이 없지 않을까 싶습니다.  그리고, softmax를 사용하지 않았다고 하신 부분에 대해서는 왜 그렇게 하셨는지 알 수 있을까요?? 또는 다른 질문사항이 있으시면 언제든지 환영입니다.

**Comment by qute012** [comment]
@sh951011 빠른 피드백에 감사드립니다. 
하이퍼 파라미터는 librosa에서 특징추출과정에 n_mels만 40으로 사용하고 나머지 하이퍼파라미터는 hparams에 정의된 것과 동일하게 사용했습니다.  본 프로젝트를 환경상 맞지 않아, 조금 수정해서 사용하였는데 전처리빼고는 동일하게 학습과 평가하였습니다. 문제점으로 예상되는 부분이 labeling 과정 중 character를 index로 변환하는 과정인데, 혹시 아래와 같은 절차가 프로젝트와 동일한지 확인부탁드립니다.
1. train set과 vaild set에서 출현하는 character들로 char2id와 id2char을 별도로 구성
2. 원-핫 임베딩 방식이 아닌 index로만 구성되게 character를 index로 변환
(e. g. ("안녕하세요.") => [6, 3, 1, 2, 5]로 구성된 텐서)

크로스 엔트로피 사용 시 softmax를 사용하지 않은 logit 자체를 넣어야된다고 보아서 그렇게 사용하였습니다. 이 부분은 제가 아직 지식이 깊지 않아서 이유를 설명하기는 어렵네요.

**Comment by sh951011** [comment]
혹시 테스트해보신 데이터가 어느 정도의 데이터인지 알 수있을까요??
보여주신 화면 상으로는 상당히 작은 데이터셋으로 보입니다.

그리고 zeroth 데이터셋이 영어데이터셋이지요??
그렇다면, 성능이 더 안 나올 수 있을 겁니다.
한글은 음소 단위가 문자 단위와 일치하지만, 영어 같은 경우는 음소 단위와 문자 단위가 일치하지 않습니다. 그래서 영어 같은 경우 음소 단위와 문자 단위 모두 연구가 활발하게 이루어지고 있습니다.
  
보통 음소 단위가 더 좋은 성능을 내는 것으로 알고 있습니다.  
그래서 성능이 더 안 좋을 수도 있을것 같다는 생각이 듭니다.  
  
그리고 train set과 valid set에서 출현하는 문자들로 별도로 구성하시면 안 됩니다.  
train dataset 내에서 train, validation 으로 나누는 것이기 때문에 같은 char2id와 id2char가 필요합니다.  만약 다르게 구성하셨다면, 해당 이유 때문에 성능이 더 안 나왔을 가능성이 커 보입니다.  
   
그리고, softmax 관련하여 말씀드리자면, 음성인식 자체가 Classification 문제입니다.  
classfication에서 softmax를 사용하지 않을 이유는 없어 보입니다.  
  
logit 자체가 제가 알기로는, softmax를 통과하여 나온 확률 값으로 알고 있습니다.  
개인적으로 굳이 softmax를 안 쓸 이유는 없어보입니다.  
  
혹시 이해가 가지 않으시거나, 다른 질문사항 언제든지 환영합니다 ^^

**Comment by qute012** [comment]
zeroth는 한글 데이터로 되어있습니다.
본 프로젝트와 똑같이 돌리는데에는 성공을 하였는데, 혹시 한 에포크를 도는데 소요된 시간이 어느정도인지 알 수 있나요?
추출된 특징을 따로 파일로 저장하지않고 학습하는 방식이라 get_item 함수 호출 시 오디오 파일을 여는데에 시간이 좀 걸리는 듯 합니다.

**Comment by sh951011** [comment]
현재 저희는 gtx 타이탄 x로 학습시, 한 에폭당 60시간 정도 소요됩니다. ( 모든 데이터에 대하여 오그멘테이션 적용시입니다. )

2020년 3월 16일 (월) 오후 7:57, DeokJin <notifications@github.com>님이 작성:

**Comment by qute012** [comment]
피드백 해주신 내용을 확인해보고, 전처리 값을 비교해보니 제 코드의 결과와는 차이가 있더라구요. 감사합니다.

에폭마다 오디오파일을 open하는 방식에서 데이터를 pickle로 저장하여 사용함은 어떤지 생각을 들어보고 싶네요.

저 같은 경우에는 배치사이즈 8에 10스텝을 돌아가는데 약 40초 정도 소모가 되어서 아래와 같이 파일로 만들어놓고 학습하려하는데 도움이 될까하여 남깁니다.

### 생성된 데이터 셋을 데이터 로더 생성
```
def _collate_fn(batch):
    """ functions that pad to the maximum sequence length """
    def seq_length_(p):
        return len(p[0])

    def target_length_(p):
        return len(p[1])

    seq_lengths = [len(s[0]) for s in batch]
    target_lengths = [len(s[1]) for s in batch]

    max_seq_sample = max(batch, key=seq_length_)[0]
    max_target_sample = max(batch, key=target_length_)[1]

    max_seq_size = max_seq_sample.size(0)
    max_target_size = len(max_target_sample)

    feat_size = max_seq_sample.size(1)
    batch_size = len(batch)

    seqs = torch.zeros(batch_size, max_seq_size, feat_size)

    targets = torch.zeros(batch_size, max_target_size).to(torch.long)
    from package.definition import PAD_TOKEN
    targets.fill_(PAD_TOKEN)

    for x in range(batch_size):
        sample = batch[x]
        tensor = sample[0]
        target = sample[1]
        seq_length = tensor.size(0)
        seqs[x].narrow(0, 0, seq_length).copy_(tensor)
        targets[x].narrow(0, 0, len(target)).copy_(torch.LongTensor(target))
    return seqs, targets, seq_lengths, target_lengths

train_dataloader = torch.utils.data.DataLoader(train_dataset_list, batch_size=hparams.batch_size, collate_fn=_collate_fn,
                                           pin_memory=True, shuffle=False, num_workers=4)
test_dataloader = torch.utils.data.DataLoader(valid_dataset_list, batch_size=hparams.batch_size, collate_fn=_collate_fn,
                                           pin_memory=True, shuffle=False, num_workers=4)
```

### 데이터를 피클로 저장
```
import time
import pickle

test_features_path = "your path"
for i, data in enumerate(tqdm(test_dataloader)):
    file_name = str(i)+'.npy'
    with open(test_features_path+file_name, 'wb') as f:
        pickle.dump(data, f)
    #finish_time = time.time()
    #print("loading time: {}".format(finish_time-start_time))
    #start_time = finish_time    

train_features_path = "your path"
for i, data in enumerate(tqdm(train_dataloader)):
    file_name = str(i)+'.npy'
    with open(train_features_path+file_name, 'wb') as f:
        pickle.dump(data, f)
    #finish_time = time.time()
    #print("loading time: {}".format(finish_time-start_time))
    #start_time = finish_time    
```

### 새로운 파일 데이터 셋 정의
```
train_features_path = "your path"
test_features_path = "your path"
import pickle
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import random

class FileDataset(Dataset):
    def __init__(self, path, sample_size=None, shuffle=True):
        self.sample = []
        for root, dirs, files in os.walk(path):
            for file in files:
                self.sample.append(os.path.join(root, file))
        #print('loading {} {} samples...'.format(len(self.samples), split))
        if sample_size:
            self.sample = self.sample[:sample_size]
        self.queue = self.sample
        self.q_idx = 0
        self.shuffle = shuffle

    def __getitem__(self, i):
        with open(self.sample[i], 'rb') as f:
            sample = pickle.load(f)
        return sample
    
    def get(self):
        try:
            with open(self.queue[self.q_idx], 'rb') as f:
                data = pickle.load(f)
            #tmp = self.queue[self.q_idx]
            self.q_idx += 1
            return data
        except:
            self.q_idx = 0
            if self.shuffle:
                random.shuffle(self.sample)
                self.queue = self.sample
            else:
                self.queue = self.sample
            return (torch.randn(0), torch.randn(0), torch.randn(0), torch.randn(0))
    
    def __len__(self):
        return len(self.sample)

class FileDataLoader(torch.utils.data.DataLoader):
    def __init__(self, train_dataset, **kwargs):
        kwargs['batch_size'] = 1
        super().__init__(train_dataset, **kwargs)
    
train_dataset = FileDataset(train_features_path)
#train_dataloader = FileDataLoader(train_dataset, batch_size=1, pin_memory=True, shuffle=True, num_workers=4)
#test_dataset = FileDataset(test_features_path, True, False)
test_dataset = FileDataset(train_features_path, shuffle=False)
#test_dataloader = FileDataLoader(test_dataset, batch_size=1, pin_memory=True, shuffle=True, num_workers=4)
```

단순한 코드이지만 첨부합니다! 피드백 감사합니다.

**Comment by qute012** [comment]
@sh951011 혹시 피라미드 구조의 rnn을 사용안하고 학습한 결과인데, LAS 논문과 똑같이 Listener에서 피라미드 구조로 rnn을 쌓았을 때의 결과도 따로 확인해보셨는지요?

**Comment by sh951011** [comment]
저희도 오디오를 미리 pickle 파일로 만들어두는 방법을 생각했었습니다만,  모든 오디오 파일의 미리 피쳐를 계산해서 pickle 파일로 로드했을 때, 60만개가 넘는 오디오 파일에 대한 MFCC or Log Mel-Spectrogram을 메모리에 저장하기에는 메모리의 한계가 있었습니다.  
  
또한 언급하신 피라미드 구조의 Listener 같은 경우는 hparams.py의 use_pyramidal 옵션을 True로 설정해주시면, 학습 가능하십니다.  
  
또한 현재 학습 진행중인 저희 모델의 경우에도 피라미드 구조의 Listener를 이용해 학습중입니다.  
여러가지 복합적인 변경사항이 있어서, 특별히 이 구조 때문이라고 하기는 뭐하지만, 학습 속도 및 인식률 면에서 빠른 학습이 진행되고 있습니다.

**Comment by sh951011** [comment]
그리고 저희는 배치사이즈 8로 학습을 진행했을때 10 스텝 당 10~20sec의 시간이 소요됩니다.

**Comment by qute012** [comment]
@sh951011 피라미드 구조로 썼을 때, timestep을 절반으로 줄이면서 연산량이 2^n으로 감소하기 때문에 학습속도가 개선되는 것으로 보입니다.

안내해주신 내용과 같이 하이퍼파라미터를 사용하였을 때, validaion cer이 변하지 않는 것을 보았습니다.  따로 학습하지 않은 모델을 sample만 예측해본 결과 별도로 구성한 character에서 4번째 인덱스인 띄어쓰기만 인식됩니다. 원래 초기의 가중치에서 이렇게 하나의 값만 예측하게 되는지 잘 모르겠습니다. 혹시 label에서 띄어쓰기를 사용하셨는지 이러한 경험을 하신적이 있으신지 궁금합니다.
![image](https://user-images.githubusercontent.com/33983084/76760893-dce45a00-67d1-11ea-92c7-a7a254f8bf83.png)

그리고 라벨 중 인덱스 0번이 의미하는 것이 무엇인지 궁금합니다
![image](https://user-images.githubusercontent.com/33983084/76761494-db676180-67d2-11ea-88b9-f8f41830b89c.png)

**Comment by sh951011** [comment]
저희 아래 레이블 파일을 확인해보시면 띄어쓰기가 포함되어 있는 것을 확인하실 수 있습니다.  
https://github.com/sh951011/Korean-Speech-Recognition/blob/master/data/label/train_labels.csv  
말씀하신 인덱스 번이 어떤 것을 말씀하시는지 잘 모르겠습니다.   
  
또한, 문의해주신 것과 같이 하나의 값만 예측하게 되는 경우는 보지 못했습니다.  
아마 어떤 부분이 잘못되었다고 생각합니다.  
  
학습 데이터가 어떤 오디오 파일인지, 어느 정도의 데이터인지 등의 정보를 알 수 있을까요??

**Comment by qute012** [comment]
@sh951011 
kaldi 프로젝트인 zeroth 데이터를 사용하였습니다.
https://github.com/goodatlas/zeroth
http://www.openslr.org/40/
데이터는 51.6시간 정도이며, 데이터 전체를 학습시킬 때 train에서 cer은 느리게 감소하는데 valid에서의 cer은 거의 변하지않고 99.xxx로 고정적으로 나옵니다.

**Comment by sh951011** [comment]
트레인 cer이 어느 정도 되는지 알 수 있을까요??
훈련되지 않은 데이터이기 때문에 train에서보다 cer이 낮은 것은 당연합니다.
  
또한  evaluate() 당시에는 티쳐포싱 없이 추론하기 때문에,  훈련이 충분히 되지 않았다면 거의 모든 정답을 틀리게 되는 것도 당연합니다.

**Comment by qute012** [comment]
@sh951011 
epoch 4에서 cer입니다. train은 0.84언저리이고 validation은 99.21 입니다. 
![image](https://user-images.githubusercontent.com/33983084/76776237-d530af80-67e9-11ea-9897-1abecef8ea1f.png)

![image](https://user-images.githubusercontent.com/33983084/76778518-55a4df80-67ed-11ea-96ff-81db0102a825.png)


모델이 결과로 다음과 같이 대부분 하나만 예측하네요.
![image](https://user-images.githubusercontent.com/33983084/76778446-33ab5d00-67ed-11ea-999f-49d2242e6aab.png)

**Comment by sh951011** [comment]
train이 0.84라는 것은 거의 못 맞추고 있는 상태입니다.  
이러한 16%라는 인식률도 티쳐포싱의 도움을 받아 나오는 인식률이기 때문에,  
학습 초반에 evaluate()를 하게 되면, 인식률이 현저히 낮아지는 것은 당연합니다. (티쳐포싱 사용하지 않기 때문)  
   
다양한 결과를 보고 싶다면, valid 데이터셋 evaluate()시에 티쳐포싱 비율을 1.0으로 줘 보시고 해보시겠어요? 어느 정도의 예측률은 나올 것이라 생각합니다.

**Comment by qute012** [comment]
@sh951011 
디버깅 과정중에 있는데, 라벨링을 다르게하니 결과가 좀 다르게 나오더군요.
![image](https://user-images.githubusercontent.com/33983084/77059949-1f4ca780-6a1b-11ea-8055-00ce1ef3f00f.png)
![image](https://user-images.githubusercontent.com/33983084/77059963-2673b580-6a1b-11ea-8e27-cd4603fc6af3.png)

id 0과 2039가 의미하는게 각각 무엇인지 알 수 있을까요?
''와 "_"입니다. "_"는 PAD_TOKEN으로 이해하고 있었는데 보통 PAD_TOKEN의 id는 0으로 사용하지않은가 해서 질문드립니다.

**Comment by sh951011** [comment]
0번은 띄어쓰기인 ' '이고, 2039번은 말씀하신 PAD_TOKEN이 맞습니다.
distance 계산시에 띄어쓰기는 빼고 계산하기 때문에, 0번으로 예측을 하기도 하더라고요

감사합니다.

2020년 3월 19일 (목) 오후 7:53, DeokJin <notifications@github.com>님이 작성:

**Comment by qute012** [comment]
LAS 모델이 한국어 기준으로 성능이 저조해보이네요.
네. 저도 다른 결과가 나오면 피드백 드릴게요! 답변 정중히 해주셔서 감사합니다.

**Comment by sh951011** [comment]
저 같은 경우는 CRR 기준 80% 이상의 인식률이 나오고 있습니다.
현재 저조하게 나오시나요??

2020년 3월 19일 (목) 오후 8:01, DeokJin <notifications@github.com>님이 작성:

**Comment by qute012** [comment]
아직 1에포크밖에 못 돌렸지만, 아마도 데이터수량이 51.6시간으로 Ai-Hub에 비해 턱없이 모잘라서 저조한 것 같군요. CRR이 15%언저리입니다.
이전에는 제가 라벨링을 0:PAD_TOKEN 1:SOS_TOKEN 2:EOS_TOKEN ... 4: \s(Space Bar) ...
로 사용하였는데 본 프로젝트와 같이 0번을 스페이스 바로 사용하니 정확도가 제대로 나오네요.
이에대한 이해가 되지는 않습니다만... 혹시 왜 그런지 알고 계시다면 설명해주시면 감사할 것 같습니다.

**Comment by sh951011** [comment]
1에폭에 CRR 15%라면 괜찮은 성적입니다.
예전 네이버 100시간 데이터로 1에폭에 6~8% 정도의 인식률 정도밖에 되지 않았었습니다.
에폭을 20~30에폭 정도는 돌아야 최종 성적이 나올 것입니다. (이는 물론 데이터셋마다 모델마다 다르겠지만요 ㅎㅎ)

아마 토큰 번호에 따라 달라지는 것이 아니라 코드 내에서 토큰 번호가 꼬여있을수도 있습니다.
제가 질문하신 분 코드를 전체를 보고 디버깅을 할 수 없기에 제가 드릴 수 있는 답은 여기까지밖에
못 드리겠네요

감사합니다.

2020년 3월 19일 (목) 오후 9:05, DeokJin <notifications@github.com>님이 작성:

**Comment by triplet02** [comment]
Kai.Lib 팀의 배세영입니다. train CER과 test CER과의 차이가 발생한다고 이슈 남겨 주셨었는데, 해당 이슈 관련 문제를 파악하고 해결하였습니다. [이곳](https://github.com/sooftware/Korean-Speech-Recognition/issues/11)을 확인해 주세요!

당초 알려드렸던 바와 같이 단순 teacher_forcing 관련 문제는 아니었습니다. hidden state를 넘겨주는 과정에서 문제가 발생하였던 것이었고, 정확하지 않은 내용으로 답변드렸던 점 죄송합니다.

앞으로도 관련하여 많은 피드백 부탁드리겠습니다!
감사합니다.
